### ISSUE TITLE
Node Lancher Fails to Launch on Win7

### ISSUE THREAD

**Issue by jason-me** [lightning-power-users/node-launcher#120]
Attempted to run Node Launcher 5.3.0 on Win& with the following results from the command line:

`C:\Users\J-Bob\Downloads>Windows.Node.Launcher.exe
[3168] PyInstaller Bootloader 3.x
[3168] LOADER: executable is C:\Users\J-Bob\Downloads\Windows.Node.Launcher.exe
[3168] LOADER: homepath is C:\Users\J-Bob\Downloads
[3168] LOADER: _MEIPASS2 is NULL
[3168] LOADER: archivename is C:\Users\J-Bob\Downloads\Windows.Node.Launcher.exe

[3168] LOADER: Extracting binaries
[3168] LOADER: Executing self as child
[3168] LOADER: set _MEIPASS2 to C:\Users\J-Bob\AppData\Local\Temp\_MEI31682
[3168] LOADER: Setting up to run child
[3168] LOADER: Creating child process
[3168] LOADER: Waiting for child process to finish...
[3208] PyInstaller Bootloader 3.x
[3208] LOADER: executable is C:\Users\J-Bob\Downloads\Windows.Node.Launcher.exe
[3208] LOADER: homepath is C:\Users\J-Bob\Downloads
[3208] LOADER: _MEIPASS2 is C:\Users\J-Bob\AppData\Local\Temp\_MEI31682
[3208] LOADER: archivename is C:\Users\J-Bob\Downloads\Windows.Node.Launcher.exe

[3208] LOADER: SetDllDirectory(C:\Users\J-Bob\AppData\Local\Temp\_MEI31682)
[3208] LOADER: Already in the child - running user's code.
[3208] LOADER: manifestpath: C:\Users\J-Bob\AppData\Local\Temp\_MEI31682\Windows
.Node.Launcher.exe.manifest
[3208] LOADER: Activation context created
[3208] LOADER: Activation context activated
[3208] LOADER: Python library: C:\Users\J-Bob\AppData\Local\Temp\_MEI31682\pytho
n37.dll
[3208] LOADER: Loaded functions from Python library.
[3208] LOADER: Manipulating environment (sys.path, sys.prefix)
[3208] LOADER: sys.prefix is C:\Users\J-Bob\AppData\Local\Temp\_MEI31682
[3208] LOADER: Pre-init sys.path is C:\Users\J-Bob\AppData\Local\Temp\_MEI31682\
base_library.zip;C:\Users\J-Bob\AppData\Local\Temp\_MEI31682
[3208] LOADER: Setting runtime options
[3208] LOADER: Bootloader option: pyi-windows-manifest-filename Windows.Node.Lau
ncher.exe.manifest
[3208] LOADER: Initializing python
[3208] LOADER: Overriding Python's sys.path
[3208] LOADER: Post-init sys.path is C:\Users\J-Bob\AppData\Local\Temp\_MEI31682
\base_library.zip;C:\Users\J-Bob\AppData\Local\Temp\_MEI31682
[3208] LOADER: Setting sys.argv
[3208] LOADER: setting sys._MEIPASS
[3208] LOADER: importing modules from CArchive
[3208] LOADER: extracted struct
[3208] LOADER: callfunction returned...
[3208] LOADER: extracted pyimod01_os_path
[3208] LOADER: callfunction returned...
[3208] LOADER: extracted pyimod02_archive
[3208] LOADER: callfunction returned...
[3208] LOADER: extracted pyimod03_importers
[3208] LOADER: callfunction returned...
[3208] LOADER: Installing PYZ archive with Python modules.
[3208] LOADER: PYZ archive: PYZ-00.pyz
[3208] LOADER: Running pyiboot01_bootstrap.py
[3208] LOADER: Running pyi_rth_multiprocessing.py
[3208] LOADER: Running pyi_rth_pkgres.py
[3208] LOADER: Running pyi_rth_win32comgenpy.py
[3208] LOADER: Running pyi_rth_qt5plugins.py
[3208] LOADER: Running run.py
Traceback (most recent call last):
  File "run.py", line 10, in <module>
  File "node_launcher\gui\launch_widget.py", line 29, in __init__
  File "node_launcher\gui\network_buttons\network_widget.py", line 28, in __init
__
  File "node_launcher\node_set\node_set.py", line 26, in __init__
  File "node_launcher\node_set\bitcoin.py", line 28, in __init__
  File "node_launcher\services\hard_drives.py", line 23, in __init__
  File "node_launcher\services\hard_drives.py", line 39, in list_partitions
  File "node_launcher\services\hard_drives.py", line 28, in get_gb
  File "lib\site-packages\psutil\__init__.py", line 1978, in disk_usage
  File "lib\site-packages\psutil\_pswindows.py", line 249, in disk_usage
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the v
olume is not corrupted
[3208] Failed to execute script run
[3208] LOADER: OK.
[3208] LOADER: Cleaning up Python interpreter.
[3168] LOADER: Back to parent (RC: -1)
[3168] LOADER: Doing cleanup
[3168] LOADER: Freeing archive status for C:\Users\J-Bob\Downloads\Windows.Node.
Launcher.exe`

**Comment by PierreRochard** [comment]
This is fixed now, thank you for reporting it!
