### ISSUE TITLE
Node Launcher fails to launch Win10

### ISSUE THREAD

**Issue by futjrn** [lightning-power-users/node-launcher#121]
listening to the podcast while I was trying this out. 
first try I downloaded from the releases and just tried to click the .exe
I've also tried to git clone from source and use the cli to run the .exe 
below is my cli when I run the .exe

 
C:\Users\lrgeo\Downloads>Windows.Node.Launcher.exe
[6584] PyInstaller Bootloader 3.x
[6584] LOADER: executable is C:\Users\lrgeo\Downloads\Windows.Node.Launcher.exe
[6584] LOADER: homepath is C:\Users\lrgeo\Downloads
[6584] LOADER: _MEIPASS2 is NULL
[6584] LOADER: archivename is C:\Users\lrgeo\Downloads\Windows.Node.Launcher.exe
[6584] LOADER: Extracting binaries
[6584] LOADER: Executing self as child
[6584] LOADER: set _MEIPASS2 to C:\Users\lrgeo\AppData\Local\Temp\_MEI65842
[6584] LOADER: Setting up to run child
[6584] LOADER: Creating child process
[6584] LOADER: Waiting for child process to finish...
[9212] PyInstaller Bootloader 3.x
[9212] LOADER: executable is C:\Users\lrgeo\Downloads\Windows.Node.Launcher.exe
[9212] LOADER: homepath is C:\Users\lrgeo\Downloads
[9212] LOADER: _MEIPASS2 is C:\Users\lrgeo\AppData\Local\Temp\_MEI65842
[9212] LOADER: archivename is C:\Users\lrgeo\Downloads\Windows.Node.Launcher.exe
[9212] LOADER: SetDllDirectory(C:\Users\lrgeo\AppData\Local\Temp\_MEI65842)
[9212] LOADER: Already in the child - running user's code.
[9212] LOADER: manifestpath: C:\Users\lrgeo\AppData\Local\Temp\_MEI65842\Windows.Node.Launcher.exe.manifest
[9212] LOADER: Activation context created
[9212] LOADER: Activation context activated
[9212] LOADER: Python library: C:\Users\lrgeo\AppData\Local\Temp\_MEI65842\python37.dll
[9212] LOADER: Loaded functions from Python library.
[9212] LOADER: Manipulating environment (sys.path, sys.prefix)
[9212] LOADER: sys.prefix is C:\Users\lrgeo\AppData\Local\Temp\_MEI65842
[9212] LOADER: Pre-init sys.path is C:\Users\lrgeo\AppData\Local\Temp\_MEI65842\base_library.zip;C:\Users\lrgeo\AppData\Local\Temp\_MEI65842
[9212] LOADER: Setting runtime options
[9212] LOADER: Bootloader option: pyi-windows-manifest-filename Windows.Node.Launcher.exe.manifest
[9212] LOADER: Initializing python
[9212] LOADER: Overriding Python's sys.path
[9212] LOADER: Post-init sys.path is C:\Users\lrgeo\AppData\Local\Temp\_MEI65842\base_library.zip;C:\Users\lrgeo\AppData\Local\Temp\_MEI65842
[9212] LOADER: Setting sys.argv
[9212] LOADER: setting sys._MEIPASS
[9212] LOADER: importing modules from CArchive
[9212] LOADER: extracted struct
[9212] LOADER: callfunction returned...
[9212] LOADER: extracted pyimod01_os_path
[9212] LOADER: callfunction returned...
[9212] LOADER: extracted pyimod02_archive
[9212] LOADER: callfunction returned...
[9212] LOADER: extracted pyimod03_importers
[9212] LOADER: callfunction returned...
[9212] LOADER: Installing PYZ archive with Python modules.
[9212] LOADER: PYZ archive: PYZ-00.pyz
[9212] LOADER: Running pyiboot01_bootstrap.py
[9212] LOADER: Running pyi_rth_multiprocessing.py
[9212] LOADER: Running pyi_rth_pkgres.py
[9212] LOADER: Running pyi_rth_win32comgenpy.py
[9212] LOADER: Running pyi_rth_qt5plugins.py
[9212] LOADER: Running run.py
Traceback (most recent call last):
  File "run.py", line 10, in <module>
  File "node_launcher\gui\launch_widget.py", line 29, in __init__
  File "node_launcher\gui\network_buttons\network_widget.py", line 28, in __init__
  File "node_launcher\node_set\node_set.py", line 26, in __init__
  File "node_launcher\node_set\bitcoin.py", line 28, in __init__
  File "node_launcher\services\hard_drives.py", line 23, in __init__
  File "node_launcher\services\hard_drives.py", line 39, in list_partitions
  File "node_launcher\services\hard_drives.py", line 28, in get_gb
  File "lib\site-packages\psutil\__init__.py", line 1978, in disk_usage
  File "lib\site-packages\psutil\_pswindows.py", line 249, in disk_usage
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted
[9212] Failed to execute script run
[9212] LOADER: OK.
[9212] LOADER: Cleaning up Python interpreter.
[6584] LOADER: Back to parent (RC: -1)
[6584] LOADER: Doing cleanup
[6584] LOADER: Freeing archive status for C:\Users\lrgeo\Downloads\Windows.Node.Launcher.exe

I noticed this, OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted
[9212] Failed to execute script run

and thought it was local, but then saw the other issues that its not working. 

hope this QA helps

**Comment by lrgeoemtry** [comment]
lmk if this is attended to ill QA your release

**Comment by TheBigCohooNah** [comment]
I believe I had the same issue when downloading and running the latest version the first time. To correct this I located the lnd.conf file (C:\Users\<username>\AppData\Local\Lnd). I renamed it to lnd_backup.conf and then reran the launcher. The launcher will create a new lnd.conf file and it should run correct.

**Comment by PierreRochard** [comment]
This will fix it https://github.com/PierreRochard/node-launcher/pull/142

**Comment by xeyaldunyasi** [comment]
In fact the launch does not proceed beyond [XXXX] LOADER: Running run.py
it was stuck at this step and the main windows does not launch at all.

**Comment by editor-Ajian** [comment]
> In fact the launch does not proceed beyond [XXXX] LOADER: Running run.py
> it was stuck at this step and the main windows does not launch at all.

Yes I have the same issue with running vision 5.6.0 on Win 10. And, I find the the 'rename' method proposed by TheBigCohooNah doesn't work. 

What can I do?

**Comment by HelgeHunding** [comment]
This won't solve the issue, but might help to debug. I experienced the same issue (on Windows 10) and thought I should take a look at it. I pulled the latest code from Github but forgot to install requirements.txt. So when I executed run.py I got the following error
```
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from node_launcher.gui.main_widget import MainWidget
  File "C:\Users\User1\Code\node-launcher\node_launcher\gui\main_widget.py", line 17, in <module>
    from node_launcher.constants import (
  File "C:\Users\User1\Code\node-launcher\node_launcher\constants.py", line 6, in <module>
    from node_launcher.logging import log
  File "C:\Users\User1\Code\node-launcher\node_launcher\logging.py", line 2, in <module>
    import structlog
ModuleNotFoundError: No module named 'structlog'
```
I installed the requirements and everything worked.

**Comment by editor-Ajian** [comment]
Sure. Method proposed by HelgeHunding works. Now I can run the  node launcher

**Comment by PierreRochard** [comment]
Thanks for the help guys! I'll make sure it's packaged properly in the next release

**Comment by Kixunil** [comment]
This seems to affect Debian 9 as well.
