### ISSUE TITLE
PermissionError: [WinError 5] Access is denied [Win10]

### ISSUE THREAD

**Issue by Freefromchainz** [lightning-power-users/node-launcher#129]
Everything is still running would like to know what these errors mean?  Just a heads up in case it becomes an issue in the future
Traceback (most recent call last):
  File "lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
  File "lib\site-packages\psutil\_pswindows.py", line 702, in exe
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\psutil\_pswindows.py", line 688, in name
  File "lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=1964)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
  File "lib\site-packages\psutil\_pswindows.py", line 690, in name
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "node_launcher\gui\network_buttons\network_widget.py", line 59, in refresh
  File "node_launcher\node_set\bitcoin.py", line 92, in find_running_node
  File "lib\site-packages\psutil\__init__.py", line 603, in name
  File "lib\site-packages\psutil\_pswindows.py", line 641, in wrapper
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=1964)

**Comment by manecosta** [comment]
This seems to be related to process checking. There's new code possibly being merged before the next release that is going to change how that is done, particularly on Windows so it's unlikely that this issue will still be valid then.

**Comment by PierreRochard** [comment]
I've added more exception handling here for now and I agree the new process checking will make this a non-issue
