### ISSUE TITLE
macOS issue

### ISSUE THREAD

**Issue by huvegi** [lightning-power-users/node-launcher#192]
* **I'm submitting a **
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
When launching LND (macOS 10.14.3), I get the following terminal output:
```2019-02-14 19:29:21.801 [INF] LTND: Version: 0.5.2-beta commit=v0.5.2-beta, build=production, logging=default
2019-02-14 19:29:21.802 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-02-14 19:29:21.805 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2019-02-14 19:29:21.818 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2019-02-14 19:29:21.821 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2019-02-14 19:29:21.821 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2019-02-14 19:29:23.475 [INF] LNWL: Opened wallet
2019-02-14 19:29:23.531 [INF] LTND: Primary chain is set to: bitcoin
unable to create chain control: unable to connect to bitcoind: Post http://127.0.0.1:8332: dial tcp 127.0.0.1:8332: connect: connection refused
2019-02-14 19:29:23.535 [INF] LTND: Shutdown complete
unable to connect to bitcoind: Post http://127.0.0.1:8332: dial tcp 127.0.0.1:8332: connect: connection refused
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```
Running the debug as directed in your Medium post, I get the following errors:
```
Exception: [Errno 2] No such file or directory: '/support/signature/loader.py'
Traceback (most recent call last):
  File "pyscript", line 23, in bootstrap
FileNotFoundError: [Errno 2] No such file or directory: '/support/signature/loader.py'
AttributeError: module 'signature_loader' has no attribute 'pyside_type_init'
Traceback (most recent call last):
  File "run.py", line 12, in <module>
  File "node_launcher/gui/main_widget.py", line 42, in __init__
  File "node_launcher/gui/network_buttons/network_widget.py", line 18, in __init__
  File "node_launcher/node_set/node_set.py", line 20, in __init__
  File "node_launcher/node_set/bitcoin.py", line 41, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'Users/****/Library/Application Support/Bitcoin/'
[94241] Failed to execute script run```
(starred out my username)

I clearly have the Bitcoin folder in Application Support, am running a full node on my computer, but it seems to be having trouble finding it?
Not sure about the earlier part of the error though...

**Comment by erickuhn19** [comment]
I'm having a similar issue. Restarted my Mac and then the launcher was no longer working. I tried opening up an older version of the launcher and now all my config docs are changed.

Exception: [Errno 2] No such file or directory: '/support/signature/loader.py'
Traceback (most recent call last):
  File "pyscript", line 23, in bootstrap
FileNotFoundError: [Errno 2] No such file or directory: '/support/signature/loader.py'
AttributeError: module 'signature_loader' has no attribute 'pyside_type_init'
Traceback (most recent call last):
  File "run.py", line 12, in <module>
  File "node_launcher/gui/main_widget.py", line 52, in __init__
  File "node_launcher/gui/settings/settings_tab_dialog.py", line 17, in __init__
  File "node_launcher/gui/settings/lnd_tab.py", line 15, in __init__
  File "node_launcher/gui/network_buttons/alias_layout.py", line 46, in set_alias
TypeError: 'PySide2.QtWidgets.QLineEdit.setText' called with wrong argument types:
  PySide2.QtWidgets.QLineEdit.setText(list)
Supported signatures:
  PySide2.QtWidgets.QLineEdit.setText(unicode)
[1246] Failed to execute script run

**Comment by PierreRochard** [comment]
Yikes! Thanks for the detailed bug reports! I'll dig into these and release a fix this week.

@erickuhn19 take a look at your lnd.conf and see if there are multiple of any params

@huvegi You're having a separate problem that I'll have to research more, as I haven't seen anyone else have that same issue

**Comment by huvegi** [comment]
Been having an issue since I first installed an earlier version of the launcher, but don’t know if it’s been the same all the way through since i just tried the debugging step. 

If it helps, I’d previously edited my bitcoin.conf file, I remember a while ago that Bitdefender (antivirus) had removed some file, but I’ve since reinstalled the node launcher multiple times with no such notifications. Bitcoin-qt runs fine and syncs the full chain.

Let me know if there’s anything else I can look into.

**Comment by erickuhn19** [comment]
I'm not sure what caused the original issue for the node launcher to not open after restart but when I opened up an older version of the node launcher, it attempted to modify my lnd.config which through everything out of wack. I went into my Mac Time Machine and restored the prior days version. Then the most recent version of the node launcher started working again.
