### ISSUE TITLE
node-launcher wont launch

### ISSUE THREAD

**Issue by JefferyLee** [lightning-power-users/node-launcher#198]
jeffery@Lis-Mac-mini:~/Downloads/Node Launcher.app/Contents/MacOS$ ./Node.Launcher.app 
Exception: [Errno 2] No such file or directory: '/support/signature/loader.py'
Traceback (most recent call last):
  File "pyscript", line 23, in bootstrap
FileNotFoundError: [Errno 2] No such file or directory: '/support/signature/loader.py'
AttributeError: module 'signature_loader' has no attribute 'pyside_type_init'
Traceback (most recent call last):
  File "run.py", line 12, in <module>
  File "node_launcher/gui/main_widget.py", line 42, in __init__
  File "node_launcher/gui/network_buttons/network_widget.py", line 18, in __init__
  File "node_launcher/node_set/node_set.py", line 24, in __init__
  File "node_launcher/node_set/lnd.py", line 67, in __init__
AttributeError: 'list' object has no attribute 'split'
[4101] Failed to execute script run

**Comment by PierreRochard** [comment]
Yikes, what does your lnd.conf file have in it? Did you manually modify it?

**Comment by PierreRochard** [comment]
Btw this is a bug in the Node Launcher, you should be able to have multiple externalip for example
