### ISSUE TITLE
Failure to run/package from source on Windows 7

### ISSUE THREAD

**Issue by brandoncurtis** [lightning-power-users/node-launcher#252]
* **I'm submitting a ...**
  - bug report

* **What is the current behavior?**

Run/packaging failure on Windows 7

* **If the current behavior is a bug, please provide the steps to reproduce**

Following the instructions in the README:

```
git clone https://github.com/lightning-power-users/node-launcher
cd node-launcher
python.exe -m venv venv
venv\Scripts\activate
pip3.7.exe install -r requirements.txt
pip3.7.exe install -r requirements-windows.txt
python.exe setup.py develop
python.exe run.py
```

This error is returned:

```
(venv) C:\Users\Win7\Desktop\node-launcher>python.exe run.py
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from node_launcher.gui.application import Application
  File "C:\Users\Win7\Desktop\node-launcher\node_launcher\gui\application.py", l
ine 1, in <module>
    from PySide2 import QtCore
  File "C:\Users\Win7\Desktop\node-launcher\venv\lib\site-packages\PySide2\__ini
t__.py", line 49, in <module>
    _setupQtDirectories()
  File "C:\Users\Win7\Desktop\node-launcher\venv\lib\site-packages\PySide2\__ini
t__.py", line 21, in _setupQtDirectories
    import shiboken2
  File "C:\Users\Win7\Desktop\node-launcher\venv\lib\site-packages\shiboken2\__i
nit__.py", line 4, in <module>
    from .shiboken2 import *
ImportError: DLL load failed: The specified module could not be found.
```

I get a similar error when I attempt to package:

```
(venv) C:\Users\Win7\Desktop\node-launcher-master>pyinstaller run-windows.spec
68 INFO: PyInstaller: 3.4
68 INFO: Python: 3.7.3
68 INFO: Platform: Windows-7-6.1.7601-SP1
68 INFO: UPX is not available.
68 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Win7\\Desktop\\node-launcher-master',
 'C:\\Users\\pierre\\PycharmProjects\\node-launcher']
68 INFO: checking Analysis
68 INFO: Building Analysis because Analysis-00.toc is non existent
68 INFO: Initializing module dependency graph...
68 INFO: Initializing module graph hooks...
68 INFO: Analyzing base_library.zip ...
2956 INFO: Analyzing hidden import 'setuptools'
2973 INFO: Processing pre-find module path hook   distutils
3892 INFO: Processing pre-find module path hook   site
3892 INFO: site: retargeting to fake-dir 'c:\\users\\win7\\desktop\\node-launche
r-master\\venv\\lib\\site-packages\\PyInstaller\\fake-modules'
5015 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
5559 INFO: Analyzing hidden import 'pypiwin32'
5559 ERROR: Hidden import 'pypiwin32' not found
5559 INFO: Analyzing hidden import 'win32timezone'
5576 INFO: running Analysis Analysis-00.toc
5593 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by c:\users\win7\desktop\node-launcher-master\venv\scripts\python.exe

5610 INFO: Caching module hooks...
5610 INFO: Analyzing run.py
6206 INFO: Processing pre-safe import module hook   six.moves
6733 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
8911 INFO: Loading module hooks...
8911 INFO: Loading module hook "hook-certifi.py"...
8911 INFO: Loading module hook "hook-distutils.py"...
8927 INFO: Loading module hook "hook-encodings.py"...
8988 INFO: Loading module hook "hook-keyring.backends.py"...
9003 INFO: Loading KWallet
9003 INFO: Loading SecretService
9003 INFO: Loading Windows
9003 INFO: Loading chainer
9003 INFO: Loading macOS
9080 INFO: Loading module hook "hook-lib2to3.py"...
9080 INFO: Loading module hook "hook-PIL.Image.py"...
9432 INFO: Loading module hook "hook-PIL.py"...
9432 INFO: Import to be excluded not found: 'FixTk'
9432 INFO: Excluding import 'PyQt5'
9432 INFO: Excluding import 'PyQt5'
9432 INFO:   Removing import of PyQt5 from module PIL.ImageQt
9432 INFO: Excluding import 'PySide'
9432 INFO:   Removing import of PySide from module PIL.ImageQt
9432 INFO: Excluding import 'tkinter'
9432 INFO:   Removing import of tkinter from module PIL.ImageTk
9432 INFO: Excluding import 'PyQt4'
9432 INFO:   Removing import of PyQt4 from module PIL.ImageQt
9432 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
9447 INFO: Import to be excluded not found: 'FixTk'
9447 INFO: Excluding import 'tkinter'
9447 INFO: Loading module hook "hook-pkg_resources.py"...
9784 INFO: Processing pre-safe import module hook   win32com
9846 INFO: Loading module hook "hook-pydoc.py"...
9846 INFO: Loading module hook "hook-pygments.py"...
10933 INFO: Loading module hook "hook-PySide2.py"...
10933 WARNING: Hidden import "numpy.core.multiarray" not found!
10933 INFO: Loading module hook "hook-PySide2.QtCore.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PySide
2\__init__.py", line 49, in <module>
    _setupQtDirectories()
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PySide
2\__init__.py", line 21, in _setupQtDirectories
    import shiboken2
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\shibok
en2\__init__.py", line 4, in <module>
    from .shiboken2 import *
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Users\Win7\AppData\Local\Programs\Python\Python37\lib\runpy.py", line
 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Win7\AppData\Local\Programs\Python\Python37\lib\runpy.py", line
 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Win7\Desktop\node-launcher-master\venv\Scripts\pyinstaller.exe\
__main__.py", line 9, in <module>
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 19, in <module>
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\hooks\hook-PySide2.QtCore.py", line 12, in <module>
    binaries = qt_plugins_binaries('codecs', namespace='PySide2')
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\utils\hooks\qt.py", line 132, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "c:\users\win7\desktop\node-launcher-master\venv\lib\site-packages\PyInst
aller\utils\hooks\qt.py", line 106, in qt_plugins_dir
    raise Exception('Cannot find {0} plugin directories'.format(namespace))
Exception: Cannot find PySide2 plugin directories
```

* **Please tell us about your environment:**

  - Operating System: Windows 7
  - Python 3.7 installed with official Windows installer

This is from the latest `master`, commit cc9c6d79bacca64269ed18f812e0e3e396ecfb19

output of `pip freeze` in the virtual environment:
```
(venv) C:\Users\Win7\Desktop\node-launcher>pip freeze
altgraph==0.16.1
atomicwrites==1.3.0
attrs==19.1.0
certifi==2019.3.9
chardet==3.0.4
colorama==0.4.1
dataclasses==0.6
entrypoints==0.3
future==0.17.1
googleapis-common-protos==1.5.9
grpcio==1.19.0
grpcio-tools==1.19.0
humanize==0.5.1
idna==2.8
Jinja2==2.10.1
keyring==19.0.1
macholib==1.11
MarkupSafe==1.1.1
more-itertools==7.0.0
pefile==2018.8.8
Pillow==6.0.0
pluggy==0.9.0
protobuf==3.7.1
psutil==5.6.1
py==1.8.0
Pygments==2.3.1
PyInstaller==3.4
PySide2==5.12.0
pytest==4.4.0
pytest-qt==3.2.2
pywin32==224
pywin32-ctypes==0.2.0
qrcode==6.1
requests==2.21.0
shiboken2==5.12.0
six==1.12.0
structlog==19.1.0
urllib3==1.24.1
webassets==0.12.1
WTForms==2.2.1
```

Do I need to install some additional dependencies, inside or outside of the venv, to get this running and packaging from source?

**Comment by PierreRochard** [comment]
Unfortunately pyside2 doesn't work with venv on Windows, try out this approach instead: https://medium.com/@pierre_rochard/node-launcher-developer-setup-on-windows-5ba6e0fbb38a
