### ISSUE TITLE
Bug: Node Launcher won't launch on MacOS X 10.11.6

### ISSUE THREAD

**Issue by LockyHere** [lightning-power-users/node-launcher#331]
I download and execute Node Launcher App and it fails.

MacOSX 10.11.6

**System Log Messages:**
30/04/2019 09:41:51.417 launchservicesd[77]: SecTaskLoadEntitlements failed error=22
30/04/2019 09:41:51.423 launchservicesd[77]: SecTaskLoadEntitlements failed error=22
30/04/2019 09:41:51.425 launchservicesd[77]: SecTaskLoadEntitlements failed error=22
30/04/2019 09:41:51.436 appleeventsd[49]: SecTaskLoadEntitlements failed error=22
30/04/2019 09:41:51.510 com.apple.xpc.launchd[1]: (Node Launcher.64032[787]) Service exited with abnormal code: 255

**MacOS Debugging Output:**
[900] Error loading Python lib '/var/folders/9t/2hwml65x79n5znpr_rqnmxz00000gn/T/_MEIF1vuFw/Python': dlopen: dlopen(/var/folders/9t/2hwml65x79n5znpr_rqnmxz00000gn/T/_MEIF1vuFw/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/9t/2hwml65x79n5znpr_rqnmxz00000gn/T/_MEIF1vuFw/Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/9t/2hwml65x79n5znpr_rqnmxz00000gn/T/_MEIF1vuFw/Python

**Comment by PierreRochard** [comment]
@LockyHere two things to try: following the developer instructions here https://github.com/lightning-power-users/node-launcher#development or updating to a newer version of macOS

I think you're getting an error because I build the Node Launcher on a newer version of macOS

**Comment by LockyHere** [comment]
Ok following the developer instructions...

After running:
`pip3.7 install -r requirements.txt`

I get this error:
```
Collecting shiboken2<=5.12.0 (from -r requirements.txt (line 20))
  ERROR: Could not find a version that satisfies the requirement shiboken2<=5.12.0 (from -r requirements.txt (line 20)) (from versions: none)
ERROR: No matching distribution found for shiboken2<=5.12.0 (from -r requirements.txt (line 20))
```

Then when I try to run:
`python setup.py develop`

I get this error:
```
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    exec(f.read(), about)
  File "<string>", line 1, in <module>
  File "/Users/Mycelium/node-launcher/node_launcher/constants.py", line 114, in <module>
    from keyring.backends.OS_X import Keyring
ModuleNotFoundError: No module named 'keyring'
```

Hopefully you can help :)
