### ISSUE TITLE
Trouble installing on Ubuntu - No module named 'grpc'

### ISSUE THREAD

**Issue by j-alden** [lightning-power-users/node-launcher#349]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**

Following the Development install section and getting errors. By the time I run `python run.py` it says `No module named 'grpc'` but I'm unable to install that module. 

* **If the current behavior is a bug, please provide the steps to reproduce**

N/A

* **What is the expected behavior?**

Running `python run.py` is successful 

* **What is the motivation / use case for changing the behavior?**

I want to run a full node :)

* **Please tell us about your environment:**

  - Operating System: [ Ubuntu 18.04.2 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I'm following the Development install section. I got to `pip3.7 install -r requirements.txt` and received an error `Failed building wheel for dbus-python`. Full terminal log here: https://pastebin.com/XuxDkUGt

I went forward with the rest of the steps to see what would happen. When I got to `python run.py` it keeps failing for various `No module named 'X'` errors. I would `pip install X` and repeat to see what new module wasn't installed. Now I've run into `No module named 'grpc'` but I'm unable to install using `pip install grpc`: 

```
josh@josh-HP-EliteBook-820-G1:~/Node Power Launcher/node-launcher$ pip install grpc
Collecting grpc
  Using cached https://files.pythonhosted.org/packages/dd/63/e25fa1e7dbbd44ae4d2d5ceb1bfef517849c854795e73d01bfd3d250a8b1/grpc-0.3-19.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g3b7nr4i/grpc/setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "/tmp/pip-build-g3b7nr4i/grpc/grpc/__init__.py", line 6, in <module>
        from .rpc import *
      File "/tmp/pip-build-g3b7nr4i/grpc/grpc/rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax
   
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g3b7nr4i/grpc/
```

Done some googling but no luck so far ([link](https://github.com/googleapis/google-cloud-python/issues/3884)). Hit a wall at this point so would greatly appreciate any help. Worst case I'll give up and get windows for the laptop.

**Comment by j-alden** [comment]
Installed Windows and I'm syncing!
