### ISSUE TITLE
"wallet already exists" error

### ISSUE THREAD

**Issue by justinmoon** [lightning-power-users/node-launcher#364]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

When I execute `run.py` from source on 6.0.5 branch, I get the following error:

```
Traceback (most recent call last):
  File "/home/justin/bin/node-launcher/node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 96, in generate_seed
    seed_password=new_seed_password
  File "/home/justin/bin/node-launcher/node_launcher/node_set/lnd_client/lnd_client.py", line 144, in generate_seed
    response = self.wallet_unlocker.GenSeed(request)
  File "/home/justin/bin/node-launcher/venv/lib/python3.7/site-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/justin/bin/node-launcher/venv/lib/python3.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "wallet already exists"
	debug_error_string = "{"created":"@1559680138.419599060","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"wallet already exists","grpc_status":2}"
```

For context, I've had node-launcher running for a few months without issue and have a few funded channels. So this isn't a new install.

  - Operating System: [ Windows | macOS | Linux ]

Arch Linux (Manjaro)

**Comment by justinmoon** [comment]
Nevermind, I changed my rpc credentials in `bitcoin.conf` and that was the issue.
