### ISSUE TITLE
tor browser download no longer present at url

### ISSUE THREAD

**Issue by ryan-lingle** [lightning-power-users/node-launcher#367]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
I was setting up the dev environment when I hit the following error:
```
Traceback (most recent call last):
  File "/Users/Ryan/code/ryan-lingle/node-launcher/node_launcher/gui/components/thread_worker.py", line 71, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/Ryan/code/ryan-lingle/node-launcher/node_launcher/node_set/lib/software.py", line 99, in download
    response.raise_for_status()
  File "/Users/Ryan/code/ryan-lingle/node-launcher/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://dist.torproject.org/torbrowser/8.0.9/TorBrowser-8.0.9-osx64_en-US.dmg
```

* **If the current behavior is a bug, please provide the steps to reproduce**
follow dev environment setup steps for macos

* **What is the expected behavior?**
download the tor browser dist into the Node Launcher support directory

* **Please tell us about your environment:**

  - Operating System: macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

If you visit the following url: https://dist.torproject.org/torbrowser/ it seems the browser version is no longer present. Indeed, I was able to get rid of the error by changing the TARGET_TOR_RELEASE constant to 8.5.1.

However, I did hit another error later on in "handle_tor_node_status_change" that may be related to my change:
```
Traceback (most recent call last):
  File "/Users/Ryan/code/ryan-lingle/node-launcher/node_launcher/node_set/node_set.py", line 32, in handle_tor_node_status_change
    self.bitcoind_node.software.update()
  File "/Users/Ryan/code/ryan-lingle/node-launcher/node_launcher/node_set/lib/software.py", line 58, in update
    self.install()
  File "/Users/Ryan/code/ryan-lingle/node-launcher/node_launcher/node_set/lib/software.py", line 119, in install
    destination=self.software_directory
  File "/Users/Ryan/code/ryan-lingle/node-launcher/node_launcher/node_set/lib/software.py", line 153, in extract
    tar.extractall(path=destination)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 2000, in extractall
    numeric_owner=numeric_owner)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 2042, in extract
    numeric_owner=numeric_owner)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 2112, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 2161, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by ryan-lingle** [comment]
On a somewhat related note:

I already have the tor browser installed in its standard directory, yet Node Launcher still attempts to download it into the Node Launcher directory. Is there any reason it has to be in that directory or can Node Launcher check to see if the executable is present before installing the dist again?
