### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Gesundeslicht** [lightning-power-users/node-launcher#388]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

* **What is the current behavior?**

Traceback (most recent call last):
  File "run.py", line 22, in <module>
    sys.exit(app.start())
  File "/home/Martin/node-launcher/node_launcher/gui/application.py", line 32, in start
    self.node_set.start()
  File "/home/Martin/node-launcher/node_launcher/node_set/node_set.py", line 27, in start
    self.tor_node.software.update()
  File "/home/Martin/node-launcher/node_launcher/node_set/lib/software.py", line 62, in update
    self.install()
  File "/home/Martin/node-launcher/node_launcher/node_set/lib/software.py", line 123, in install
    destination=self.software_directory
  File "/home/Martin/node-launcher/node_launcher/node_set/lib/software.py", line 155, in extract
    with tarfile.open(source) as tar:
  File "/usr/local/lib/python3.7/tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

[issue.txt](https://github.com/lightning-power-users/node-launcher/files/3525340/issue.txt)

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**
To install Tor/TorBrowser and proceed with the installation...

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]
$ uname --all
Linux HP-8760w 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Yikes, thanks for reporting! I will try to reproduce on debian
