### ISSUE TITLE
WinOS Install fail

### ISSUE THREAD

**Issue by RickyBobbyBTC** [lightning-power-users/node-launcher#392]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

Install window crashes quickly......was able to grab this:

-----

[4280] LOADER: Running pyi_rth_multiprocessing.py
[4280] LOADER: Running pyi_rth_pkgres.py
[4280] LOADER: Running pyi_rth_win32comgenpy.py
[4280] LOADER: Running pyi_rth_pyside2.py
[4280] LOADER: Running run.py
Traceback (most recent call last):
  File "run.py", line 7, in <module>
  File "c:\users\pierre\src\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "node_launcher\gui\application.py", line 1, in <module>
  File "c:\users\pierre\src\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\PySide2\__init__.py", line 49, in <module>
  File "lib\site-packages\PySide2\__init__.py", line 21, in _setupQtDirectories
  File "c:\users\pierre\src\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\shiboken2\__init__.py", line 4, in <module>
ImportError: DLL load failed: The specified module could not be found.
[4280] Failed to execute script run
[4280] LOADER: OK.
[4280] LOADER: Cleaning up Python interpreter.
[3836] LOADER: Back to parent (RC: -1)
[3836] LOADER: Doing cleanup

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by patrickvdv** [comment]
On Windows 10 Pro
Same issue here, 6.0.5 installation/runs without issues but 6.0.6 installations fails with the following popup: Fatal error detected / Failed to execute script run

**Comment by patrickvdv** [comment]
Just did a retry with version 6.0.7 but still the same popup: Fatal error detected / Failed to Execute script run. With the debug installer this is the complete log:

C:\Users\patrickv\Downloads>Debug.Windows.Node.Launcher.6.0.7.exe
[6460] PyInstaller Bootloader 3.x
[6460] LOADER: executable is C:\Users\patrickv\Downloads\Debug.Windows.Node.Launcher.6.0.7.exe
[6460] LOADER: homepath is C:\Users\patrickv\Downloads
[6460] LOADER: _MEIPASS2 is NULL
[6460] LOADER: archivename is C:\Users\patrickv\Downloads\Debug.Windows.Node.Launcher.6.0.7.exe
[6460] LOADER: Extracting binaries
[6460] LOADER: Executing self as child
[6460] LOADER: set _MEIPASS2 to C:\Users\patrickv\AppData\Local\Temp\_MEI64602
[6460] LOADER: Setting up to run child
[6460] LOADER: Creating child process
[6460] LOADER: Waiting for child process to finish...
[7708] PyInstaller Bootloader 3.x
[7708] LOADER: executable is C:\Users\patrickv\Downloads\Debug.Windows.Node.Launcher.6.0.7.exe
[7708] LOADER: homepath is C:\Users\patrickv\Downloads
[7708] LOADER: _MEIPASS2 is C:\Users\patrickv\AppData\Local\Temp\_MEI64602
[7708] LOADER: archivename is C:\Users\patrickv\Downloads\Debug.Windows.Node.Launcher.6.0.7.exe
[7708] LOADER: SetDllDirectory(C:\Users\patrickv\AppData\Local\Temp\_MEI64602)
[7708] LOADER: Already in the child - running user's code.
[7708] LOADER: manifestpath: C:\Users\patrickv\AppData\Local\Temp\_MEI64602\Debug.Windows.Node.Launcher.exe.manifest
[7708] LOADER: Activation context created
[7708] LOADER: Activation context activated
[7708] LOADER: Python library: C:\Users\patrickv\AppData\Local\Temp\_MEI64602\python37.dll
[7708] LOADER: Loaded functions from Python library.
[7708] LOADER: Manipulating environment (sys.path, sys.prefix)
[7708] LOADER: sys.prefix is C:\Users\patrickv\AppData\Local\Temp\_MEI64602
[7708] LOADER: Pre-init sys.path is C:\Users\patrickv\AppData\Local\Temp\_MEI64602\base_library.zip;C:\Users\patrickv\AppData\Local\Temp\_MEI64602
[7708] LOADER: Setting runtime options
[7708] LOADER: Bootloader option: pyi-windows-manifest-filename Debug.Windows.Node.Launcher.exe.manifest
[7708] LOADER: Initializing python
[7708] LOADER: Overriding Python's sys.path
[7708] LOADER: Post-init sys.path is C:\Users\patrickv\AppData\Local\Temp\_MEI64602\base_library.zip;C:\Users\patrickv\AppData\Local\Temp\_MEI64602
[7708] LOADER: Setting sys.argv
[7708] LOADER: setting sys._MEIPASS
[7708] LOADER: importing modules from CArchive
[7708] LOADER: extracted struct
[7708] LOADER: callfunction returned...
[7708] LOADER: extracted pyimod01_os_path
[7708] LOADER: callfunction returned...
[7708] LOADER: extracted pyimod02_archive
[7708] LOADER: callfunction returned...
[7708] LOADER: extracted pyimod03_importers
[7708] LOADER: callfunction returned...
[7708] LOADER: Installing PYZ archive with Python modules.
[7708] LOADER: PYZ archive: PYZ-00.pyz
[7708] LOADER: Running pyiboot01_bootstrap.py
[7708] LOADER: Running pyi_rth_multiprocessing.py
[7708] LOADER: Running pyi_rth_pkgres.py
[7708] LOADER: Running pyi_rth_win32comgenpy.py
[7708] LOADER: Running pyi_rth_pyside2.py
[7708] LOADER: Running pyi_rth_certifi.py
[7708] LOADER: Running run.py
Traceback (most recent call last):
  File "run.py", line 7, in <module>
  File "c:\users\pierre\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "node_launcher\gui\application.py", line 1, in <module>
  File "c:\users\pierre\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\PySide2\__init__.py", line 51, in <module>
  File "site-packages\PySide2\__init__.py", line 21, in _setupQtDirectories
  File "c:\users\pierre\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\shiboken2\__init__.py", line 27, in <module>
ImportError: DLL load failed: The specified module could not be found.
[7708] Failed to execute script run
[7708] LOADER: OK.
[7708] LOADER: Cleaning up Python interpreter.
[6460] LOADER: Back to parent (RC: -1)
[6460] LOADER: Doing cleanup
[6460] LOADER: Freeing archive status for C:\Users\patrickv\Downloads\Debug.Windows.Node.Launcher.6.0.7.exe
